# Generated by Django 5.2 on 2025-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('datafono', 'Datafono'), ('qr', 'QR')], max_length=10)),
                ('fecha_pago', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
