# Generated by Django 5.2 on 2025-04-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('reservada', 'Reservada'), ('ocupada', 'Ocupada')], max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='foto')),
            ],
        ),
    ]
