name: Django DevOps CI

on:
  push:
    branches: [master, desarrollo-dayana]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Verificar estilo de código
      run: flake8 . || echo "Errores de estilo detectados"

    - name: Verificar si faltan migraciones
      run: python manage.py makemigrations --check --dry-run

    - name: Aplicar migraciones
      run: python manage.py migrate

    - name: Ejecutar pruebas
      run: python manage.py test
